import { grabar } from "./director2.mjs"; import { gerente, tb, arriba, bajar, res, clic } from "./v2lib.mjs"; import { sembrarCitas } from "./seed.mjs";
await grabar("agenda", { preparar: async (p) => { const { loginGerente } = await import("./harness2.mjs"); await loginGerente(p); await sembrarCitas(p); await p.reload(); await p.waitForTimeout(1500); await p.evaluate(() => abrirTab("agenda")); await p.waitForTimeout(1200); } }, async (a) => {
  const { p } = a;
  await a.intro("Agenda", "Las citas que reservan los clientes en la web", 9);
  await a.paso2("Para qué sirve", "La Agenda es el calendario de citas. Cuando un cliente reserva hora desde la web, la cita aparece aquí sola, sin que tengas que apuntar nada. También sirve para cerrar los días en que no se puede reservar, como vacaciones o festivos.", async () => { await res(a, "#s-agenda .head", 1500); });
  await a.paso2("La lista de citas", "Las citas están agrupadas por día, empezando por hoy. Cada una dice la hora, el nombre del cliente, su teléfono, qué coche trae y qué necesita. La siguiente cita lleva una etiqueta que dice Próxima, para que sepas a quién esperas ahora. Solo salen citas futuras y que no se han cancelado.", async () => { await res(a, "article.cita-item", 3500); });
  await a.paso2("Visita o taller", "Cada cita tiene una etiqueta. Visita quiere decir que viene a ver o probar un coche. Taller quiere decir que trae su coche para repararlo. Así sabes si tienes que preparar un coche o un hueco en el taller.", async () => { await res(a, "article.cita-item", 2000); });
  await a.paso2("Recordar la cita por WhatsApp", "La tarde antes de la cita, pulsa Recordar por WhatsApp. Se abre WhatsApp con un mensaje ya escrito, con el día, la hora y la dirección del taller. Solo tienes que enviarlo. Esto hace que muchos menos clientes se olviden de venir.", async () => { await res(a, "text=Recordar por WhatsApp", 2600); });
  await a.paso2("Llamar al cliente", "Si prefieres hablar, el botón Llamar marca su número directamente desde el móvil. Úsalo si hay que cambiar la hora o si el cliente no contesta al mensaje.", async () => { await res(a, "article.cita-item >> text=Llamar", 2000); });
  await a.paso2("Cuando el cliente viene", "Cuando el cliente llega, pulsa Hecha. La cita desaparece de la lista y el cliente pasa a Ganada en el CRM. Así la lista de hoy solo enseña lo que falta por pasar.", async () => { await clic(a, "article.cita-item >> text=Hecha", 1800); });
  await a.paso2("Cancelar una cita", "Si el cliente no puede venir, pulsa Cancelar cita y confirma. La hora vuelve a estar libre en la web al momento, y otra persona puede reservarla. Ojo: el panel no avisa al cliente, así que escríbele tú para despedirte con cariño.", async () => { await res(a, "article.cita-item >> text=Cancelar", 2400); });
  await a.paso2("Cerrar un día", "Más abajo está Días cerrados. Si vas a estar de vacaciones o es festivo, elige la fecha y pulsa Cerrar ese día. A partir de ahí, la web no ofrece ese día a nadie. Las citas que ya existían no se borran, ojo.", async () => { await p.locator("#cierre-f").scrollIntoViewIfNeeded().catch(() => {}); await a.sleep(500); await res(a, "#cierre-f", 1100); await res(a, "#cierre-add", 1800); });
  await a.paso2("Volver a abrir un día", "Para volver a abrir un día cerrado, tócalo en la lista de días cerrados y vuelve a estar disponible. Estos días también cuentan en el Dashboard para calcular las horas pagadas de los mecánicos. Y así de sencilla es la Agenda.", async () => { await res(a, "#cierre-f", 1500); });
  await a.fin("Agenda al día");
});
