import { grabar } from "./director2.mjs"; import { gerente, tb, arriba, bajar, res, clic } from "./v2lib.mjs";
await grabar("equipo", { preparar: async (p) => { const { loginGerente } = await import("./harness2.mjs"); await loginGerente(p); await p.evaluate(() => abrirTab("ordenes")); await p.waitForTimeout(1500); } }, async (a) => {
  const { p } = a;
  await a.intro("Equipo y ajustes", "Dar de alta a las personas del taller y fijar las tarifas", 9);
  await a.paso2("Para qué sirve", "Aquí das de alta a las personas que trabajan en el taller y eliges sus permisos. También fijas el precio de la hora de trabajo. Solo lo ve el gerente.", async () => { await res(a, "[data-tequipo]:visible", 1800); });
  await a.paso2("Abrir Equipo y ajustes", "Arriba a la derecha está el botón Equipo y ajustes. Púlsalo y se abre un panel por el lateral.", async () => { await clic(a, "[data-tequipo]:visible", 1800); });
  await a.paso2("Cómo entra el equipo", "Primero te cuenta cómo entra cada persona. Abre la dirección del panel en su móvil, pulsa Entrar como equipo del taller y escribe su usuario y su PIN. Solo ve el taller, nunca el dinero.", async () => { await res(a, "#dw-body .dw-box:first-of-type", 2800); });
  await a.paso2("El equipo", "Aquí está la lista de personas. Cada una tiene su puesto: mecánico, recepción, control de calidad u otros. Puedes cambiar su nombre, su usuario, su PIN o sus horas al día.", async () => { await res(a, "#dw-body .t-per", 2800); });
  await a.paso2("Añadir una persona", "Para añadir a alguien, abre Añadir persona. Escribe su nombre y un usuario fácil de recordar. Elige su puesto, cuántas horas se le pagan al día y su fecha de alta.", async () => { await p.evaluate(() => { const d = document.querySelector(".t-nueva"); if (d) d.open = true; }); await a.sleep(500); await a.escribir('.t-nueva [name="nombre"]', "Marta Díaz"); await a.escribir('.t-nueva [name="usuario"]', "marta", 500); });
  await a.paso2("El PIN y la caja", "Ponle un PIN de seis números. Y marca, si quieres, que puede usar la caja. Solo dáselo a quien de verdad lo necesite, porque es dinero.", async () => { await a.escribir('.t-nueva [name="pin"]', "654321"); await res(a, '.t-nueva [name="caja"]', 1600); });
  await a.paso2("Dar de baja", "Si alguien deja de trabajar con vosotros, pulsa Dar de baja. Ya no podrá entrar. No se borra nada: sus fichajes siguen contando en los informes.", async () => { await bajar(a, 250); await a.sleep(1500); });
  await a.paso2("Ajustes del taller", "Abajo están los ajustes. La tarifa de mano de obra es el precio de una hora de trabajo, sin impuesto. El porcentaje de aviso sirve para que, si un trabajo tarda mucho más de lo previsto, el mecánico tenga que explicar por qué. Y aquí fijas el IGIC.", async () => { await p.evaluate(() => { const f = document.querySelector("[data-tcfg]"); if (f) f.scrollIntoView({ block: "center", behavior: "smooth" }); }); await a.sleep(2400); });
  await a.paso2("Guardar", "Cuando termines, pulsa Guardar ajustes. Y listo: los cambios se aplican al momento en todo el panel. Y así termina Equipo y ajustes.", async () => { await res(a, "[data-tcfg] button", 2200); });
  await a.fin("Equipo configurado");
});
