import { grabar } from "./director2.mjs"; import { gerente, tb, arriba, bajar, res, clic } from "./v2lib.mjs";
await grabar("fin", gerente("fin"), async (a) => {
  const { p } = a;
  await a.intro("Finanzas", "Todo el dinero del negocio en un solo sitio", 13);
  await a.paso2("Para qué sirve", "Finanzas junta los ingresos y los gastos del taller, de la venta de coches y de la caja. No hace falta apuntar nada dos veces. También prepara los documentos para la gestoría.", async () => { await res(a, "#s-fin .head", 1500); });
  await a.paso2("Elegir el periodo", "Arriba eliges si quieres mirar un día, una semana, un mes o un año. Las flechas te mueven al periodo anterior o al siguiente. Todos los números cambian con tu elección.", async () => { await clic(a, "[data-fnper=semana]", 800); await clic(a, "[data-fnper=mes]", 1000); await clic(a, "[data-fnper=anio]", 800); await clic(a, "[data-fnper=mes]", 700); });
  await a.paso2("Los números principales", "Estas tarjetas cuentan cómo va el dinero: cuánto entra, cuánto sale, el beneficio y el efectivo que hay. El efectivo se compara con los cierres de caja. Si sale un descuadre, aquí lo verás.", async () => { await res(a, "#s-fin .kpis, #s-fin .grid, #s-fin .card", 3000); });
  await a.paso2("Los gráficos", "Los gráficos dicen dónde se gana y dónde se gasta. Uno compara la rentabilidad del taller con la de los coches. Otro enseña a dónde se va el dinero, y otro cómo te pagan los clientes: efectivo, tarjeta o transferencia.", async () => { await bajar(a, 450); await a.sleep(2200); });
  await a.paso2("Pendientes", "En Pendientes está lo que falta por hacer: lo que hay por cobrar, las ventas de coches por completar y las salidas de caja sin clasificar. Si todo está al día, esta zona está vacía.", async () => { await bajar(a, 450); await a.sleep(2200); });
  await a.paso2("Apuntar un gasto", "Vamos a apuntar una factura. Pulsa menos Nuevo gasto.", async () => { await arriba(a); await clic(a, "[data-fngasto]", 1300); });
  await a.paso2("Rellenar el gasto", "Escribe el proveedor, el concepto y la categoría, por ejemplo recambios. Elige si es del taller, de la venta o de otros. Escribe la base, que es el importe sin impuesto, y elige cómo se pagó.", async () => { await a.elegir("#fn-cat", "recambios").catch(() => {}); await clic(a, "dialog[open] [data-v=taller]", 400); await a.escribir("#fn-prov", "Recambios Sur"); await a.escribir("#fn-fact", "F-2026-0142"); await a.escribir("#fn-con", "Pastillas de freno y discos"); await a.escribir("#fn-base", "185,40"); await clic(a, "dialog[open] [data-v=tarjeta]", 600); await p.locator("dialog[open] input[data-fnfile]").nth(1).setInputFiles("/tmp/ticket.png").catch(() => {}); await a.sleep(900); });
  await a.paso2("Guardar el gasto", "Adjunta una foto o el PDF de la factura y pulsa Guardar gasto. El impuesto y los totales se calculan solos. Si pagas en efectivo, el dinero sale de la caja abierta de hoy.", async () => { await clic(a, "#fn-ok", 1800); });
  await a.paso2("Cobrar con tarjeta o transferencia", "En Por cobrar, junto a cada orden, pulsa Registrar cobro. Escribes cuánto ha pagado el cliente y cómo. Los presupuestos aceptados entran solos como ingreso, así que no los apuntes otra vez.", async () => { await bajar(a, 300); await a.sleep(1800); });
  await a.paso2("Completar la venta de un coche", "Cuando vendes un coche, pulsa Completar venta. Escribe el precio final, el comprador, la fecha y lo que costó el coche. Así el panel calcula cuánto has ganado con ese coche. Ojo: los pagos en efectivo de mil euros o más no están permitidos, pregunta a tu gestoría.", async () => { await a.sleep(500); });
  await a.paso2("Clasificar las salidas de caja", "Las salidas de caja que no tienen categoría salen aquí. Ábrelas y elige a qué pertenecen: recambios, suministros, mantenimiento. Los retiros del propietario no son gastos, solo cambian el dinero de sitio.", async () => { await a.sleep(500); });
  await a.paso2("Facturas emitidas y recibidas", "Abajo están las facturas emitidas, que son ingresos, y las recibidas, que son gastos, cada una con su archivo. No se borran: se anulan con un motivo.", async () => { await bajar(a, 600); await a.sleep(1800); });
  await a.paso2("Para la gestoría", "A final de trimestre, elige el periodo y pulsa Excel emitidas, Excel recibidas y PDF asesoría. Envía esos tres archivos a tu gestoría y ya está. Así termina Finanzas.", async () => { await arriba(a); await res(a, "[data-fnexp=emitidas]", 1200); await res(a, "[data-fnexp=pdf]", 1800); });
  await a.fin("Cuentas al día");
});
