import { grabar } from "./director2.mjs"; import { BASE, CLAVE } from "./harness2.mjs";
await grabar("inicio", { gerente: false, preparar: async (p) => { await p.goto(BASE + "/admin.html"); await p.waitForTimeout(700); } }, async (a) => {
  const { p } = a;
  await a.intro("Primeros pasos", "Entrar al panel y saber qué hace cada pestaña", 12);
  await a.paso2("Esta es la puerta del panel", "Vamos a aprender a usar el panel de Volcano Cars, paso a paso, como si fuera tu primer día. Esta pantalla es la puerta de entrada. Para pasar necesitas una llave: o una contraseña, o un usuario con su PIN.", async () => { await a.resaltar("#pw", 1200); });
  await a.paso2("Dos formas de entrar", "El gerente entra con su contraseña. El equipo del taller, es decir, recepción, mecánico y calidad, entra con su usuario y su PIN, que son unos números secretos que da el gerente. Debajo del botón Entrar puedes cambiar de una forma a otra.", async () => { await a.resaltar("#login-modo", 1200); await a.click("#login-modo", 2500); await a.click("#login-modo", 500); });
  await a.paso2("Escribe tu contraseña", "Como gerente, pulsa en la casilla y escribe tu contraseña. Los puntitos esconden las letras para que nadie te las vea. Si te equivocas varias veces seguidas, el panel te deja descansar un rato antes de volver a intentarlo.", async () => { await a.escribir("#pw", CLAVE, 400); });
  await a.paso2("Pulsa Entrar", "Ahora pulsa el botón Entrar. Si tienes activada la verificación en dos pasos, te pedirá un código de seis cifras que sale en el móvil. Es como una segunda llave extra para que nadie entre por ti.", async () => { await a.click("#login-btn", 1800); });
  await a.paso2("La barra de arriba", "¡Ya estás dentro! Arriba del todo ves tu nombre y tu puesto. Con el botón Ver web abres la página pública que ven los clientes, y con Salir cierras tu sesión cuando terminas. Es importante salir en ordenadores compartidos.", async () => { await a.resaltar("#topacts", 1800); });
  await a.paso2("Las pestañas del negocio", "Debajo hay las pestañas. Cada una es una parte del negocio, como las habitaciones de una casa. Dashboard enseña los números. CRM guarda a los clientes. Taller lleva los coches que se reparan. Inventario cuenta recambios y herramientas.", async () => { await a.resaltar("#tabs", 3000); });
  await a.paso2("Más pestañas", "Control de Caja guarda el dinero en efectivo. Jornada es el fichaje de entrada y salida del equipo. Finanzas junta gastos e ingresos para la gestoría. Agenda enseña las citas. Coches es donde se publican los coches en venta. Respuestas ayuda a contestar reseñas y mensajes. Y Ayuda eres tú ahora mismo.", async () => { await a.resaltar("#tabs", 3000); });
  await a.paso2("Los números rojos", "Fíjate en los numeritos al lado de algunas pestañas. Si hay un número, significa que hay cosas pendientes: clientes sin contestar, citas de hoy o alertas. Cuando lo ves, sabes dónde tienes que ir primero.", async () => { await a.resaltar("#tabs", 2200); });
  await a.paso2("Abre una pestaña", "Para abrir una pestaña, solo tienes que tocarla. Vamos a probar con el CRM, que es la agenda de clientes del negocio.", async () => { await a.click('[data-tab="leads"]', 1600); });
  await a.paso2("El botón ¿Cómo funciona?", "En cada pestaña, arriba, hay un enlace pequeño que dice Cómo funciona. Si tienes una duda en cualquier pantalla, púlsalo y te lleva directo a su ayuda, con vídeo y pasos escritos.", async () => { await a.resaltar("#s-leads [data-ayuda]", 2400); });
  await a.paso2("Los paneles que se abren al lado", "Cuando tocas un cliente o una orden, se abre un panel a la derecha con toda su información. Se cierra con la equis de arriba. Así nunca pierdes el sitio donde estabas.", async () => { await p.waitForTimeout(500); });
  await a.paso2("Esta pestaña de Ayuda", "Y aquí, en Ayuda, tienes un vídeo largo por cada pestaña, explicado paso a paso. A la izquierda eliges la sección. Debajo del vídeo hay un interruptor para oír la voz. Tú decides: mirar, escuchar o leer los pasos por escrito.", async () => { await p.evaluate(() => abrirTab("ayuda")); await p.waitForTimeout(1500); await a.resaltar(".ay-nav", 2400); });
  await a.fin("Ya sabes moverte");
});
