import { grabar } from "./director2.mjs"; import { gerente, tb, arriba, bajar, res, clic } from "./v2lib.mjs";
await grabar("propios", { preparar: async (p) => { const { loginGerente } = await import("./harness2.mjs"); await loginGerente(p); await p.evaluate(() => abrirTab("ordenes")); await p.waitForTimeout(1200); await p.click('[data-tvista="propios"]'); await p.waitForTimeout(1500); } }, async (a) => {
  const { p } = a;
  await a.intro("Coches propios", "Los coches del negocio que se preparan para vender", 10);
  await a.paso2("Para qué sirve", "Aquí van los coches del negocio, los coches de stock. El negocio no compra coches a los clientes: esta lista es solo para controlar cada coche nuestro mientras se arregla y se prepara para venderlo. Es interna: nada de esto sale en la web.", async () => { await res(a, "#ordenes .card", 1500); });
  await a.paso2("Las fases", "Arriba hay filtros por fase. En el taller, Entrada o dañado, En reparación, Control de calidad, Listo para venta y Vendidos. Cada número dice cuántos coches hay en esa fase. Así ves de un vistazo en qué punto está cada coche.", async () => { await res(a, ".segv, .vp-filtros, #ordenes .chips", 3000); });
  await a.paso2("Añadir un coche nuevo", "Para meter un coche en la lista, pulsa más Coche que entra. Es lo que haces cuando un coche del negocio llega al taller para prepararlo.", async () => { await clic(a, "[data-vpnuevo]", 1300); });
  await a.paso2("Los datos del coche", "Escribe la marca y el modelo, que son obligatorios. Si puedes, añade la matrícula, el año, los kilómetros, el color y el bastidor. En Daños o trabajo a hacer, cuenta qué hay que arreglar.", async () => { await a.escribir("#vp-mar", "Seat"); await a.escribir("#vp-mod", "Ibiza"); await a.escribir("#vp-mat", "5678LMN"); await a.escribir("#vp-anio", "2017"); await a.escribir("#vp-km", "112000"); await a.escribir("#vp-dan", "Pintar paragolpes y cambiar pastillas", 500); });
  await a.paso2("Coste y precio", "El gerente escribe el coste del coche y el precio de venta previsto, sin impuesto. Así el panel calcula cuánto ganarás cuando se venda. El mecánico no ve estos números.", async () => { await a.escribir("#vp-com", "6200"); await a.escribir("#vp-pre", "9500", 500); });
  await a.paso2("Guardar", "Pulsa Guardar. El coche aparece en la lista, con su ficha. Si es de la web, puedes enlazarlo con el coche que está publicado.", async () => { await clic(a, "#vp-ok", 1800); });
  await a.paso2("La ficha del coche", "Si tocas un coche, se abre su ficha. Aquí ves el resumen de costes: lo que costó el coche, las piezas que se cogieron del inventario, las horas de mano de obra y otros gastos aprobados. Y debajo, el total y el beneficio previsto.", async () => { await clic(a, ".vp-card", 2200); });
  await a.paso2("Mover de fase", "Cuando el coche avanza, cambias su fase: de entrada a reparación, de reparación a control de calidad, y por último, listo para venta. Cada cambio queda guardado con quién lo hizo y cuándo.", async () => { await res(a, "[data-vpfase], #ordenes select, #ordenes .segv", 2600); });
  await a.paso2("Piezas, horas y costes", "Las piezas que cargas desde aquí se descuentan del Inventario. Las horas salen de los tiempos del taller. Y otros gastos, como pintura o grúa, se anotan con Anotar un coste. Si lo propone el mecánico, el gerente lo revisa antes de que cuente.", async () => { await bajar(a, 500); await a.sleep(1500); });
  await a.paso2("Coste por hora y registro", "Arriba, Coste por hora fija lo que cuesta una hora de mano de obra. Y Registro guarda la historia de todos los coches, con cada cambio. Con esto, sabes siempre cuánto cuesta preparar cada coche de stock.", async () => { await arriba(a); await p.evaluate(() => document.querySelector("[data-vpvolver]")?.click()); await a.sleep(800); await res(a, "[data-vpcfg]", 1300); await res(a, "[data-vplib], [data-vpreg]", 1500); });
  await a.fin("Coches de stock al día");
});
