import { grabar } from "./director2.mjs"; import { gerente, tb, arriba, bajar, res, clic } from "./v2lib.mjs";
await grabar("resp", gerente("resp"), async (a) => {
  const { p } = a;
  await a.intro("Respuestas", "Contestar reseñas y mensajes sin pensar qué escribir", 10);
  await a.paso2("Para qué sirve", "Esta pestaña te escribe las respuestas. Si un cliente deja una reseña en Google, o te escribe por WhatsApp o por Instagram, eliges el caso y el panel te da un texto listo para copiar. Así contestas rápido, con educación y sin faltas.", async () => { await res(a, "#s-resp .head", 1500); });
  await a.paso2("Los tres canales", "Arriba eliges dónde vas a contestar: reseñas de Google, WhatsApp, o Instagram y Facebook. Cada canal tiene sus propios textos.", async () => { await res(a, ".rs-canales", 2600); });
  await a.paso2("Reseñas de Google: el nombre", "En Google, primero escribe el nombre del cliente tal cual aparece en su reseña. La respuesta empezará saludándole por su nombre.", async () => { await clic(a, '[data-rscanal="google"]', 600); await a.escribir("#rs-nombre", "Bunny Green", 400); });
  await a.paso2("Las estrellas", "Después toca las estrellas que puso: de cinco a una. Con cinco estrellas, la respuesta da las gracias. Con una o dos, pide perdón y ofrece una solución.", async () => { await clic(a, '[data-rsest="5"]', 900); await clic(a, '[data-rsest="2"]', 900); await clic(a, '[data-rsest="5"]', 700); });
  await a.paso2("El tipo de reseña y el servicio", "Elige qué tipo de reseña es y qué servicio usó, por ejemplo taller o compra de un coche. Y si quieres, marca hasta dos cosas que destaca, como el trato o la rapidez. Así la respuesta suena a una persona real.", async () => { await res(a, ".rs-chips", 3000); await clic(a, "[data-rsserv]", 700); await clic(a, "[data-rsdest]", 700); });
  await a.paso2("Idioma, español o inglés", "Si el cliente escribió en inglés, pulsa English y la respuesta sale en inglés. En la isla vienen muchos turistas, así que esto ayuda mucho.", async () => { await clic(a, '[data-rsidi="en"]', 1200); await clic(a, '[data-rsidi="es"]', 900); });
  await a.paso2("Tu respuesta", "Abajo aparece tu respuesta. Puedes leerla y cambiarla si quieres. Si no te gusta, pulsa Otra versión y sale un texto distinto.", async () => { await bajar(a, 350); await clic(a, "[data-rsotra]", 1400); });
  await a.paso2("Copiar y pegar", "Pulsa Copiar respuesta, y después Abrir mis reseñas. Se abre Google. Pega la respuesta, y ya está. Una respuesta rápida a cada reseña mejora la imagen del negocio.", async () => { await clic(a, "[data-rscopiar]", 1600); });
  await a.paso2("WhatsApp: mensajes ya escritos", "En WhatsApp hay mensajes preparados: para confirmar una cita, mandar un presupuesto, avisar de que el coche está listo y más. Escribe el nombre, el coche, el día y la hora, y todos los mensajes se rellenan solos. Pulsas el botón de WhatsApp y se abre con el texto escrito.", async () => { await arriba(a); await clic(a, '[data-rscanal="whatsapp"]', 1200); await a.escribir("#rs-wn", "Pedro"); await a.escribir("#rs-wc", "Seat Ibiza"); await a.escribir("#rs-wq", "el martes a las 10:00", 600); await bajar(a, 400); await a.sleep(1500); });
  await a.paso2("Instagram y Facebook", "En Instagram y Facebook pasa igual: mensajes listos para copiar. Abajo, hay una guía para activar respuestas automáticas, que se configura una sola vez. Y así termina Respuestas.", async () => { await arriba(a); await clic(a, '[data-rscanal="redes"]', 1500); await bajar(a, 700); await a.sleep(1200); });
  await a.fin("Respuestas listas");
});
